### PR TITLE
added Request tab under Admin

### LINKED ISSUE #24: Add an admin tab to the Navbar

### PR DESCRIPTION
**Pull request by bgggggh**
Close #24 
I added "Request" tab under Admin on the Navbar. Additionally, we added routing to display the correct page to the user. 
截屏2024-11-25 上午12 25 49

Deployment: https://rec-qa.dokku-05.cs.ucsb.edu/

### CODE REVIEW

**Review by basperheim1 — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM..

**Review by pconrad — CHANGES_REQUESTED** [review]
Actually, looking at this again, no this does not LGTM.

This adds Requests under the Admin menu; it makes no sense there.

We need a place for:
* Regular users to be able to create requests
* Regular users to be able to list and edit requests (but only their own)
* Admins/Instructors to be able to respond to requests.

It it's present form, this doesn't seem to advance any goal related to the actual use cases for the application, so I can't approve this.

**Comment by pconrad** [comment]
Ok, I do now see that Issue #16 is tangentially related to what is being added here.

But the placeholder page isn't even a reasonable placeholder page for the use case specified; it's a repurposed placeholder from the old team02 code base, and there isn't time at this point to replace it with anything reasonable.

I think this PR just adds too little value to be worth merging.

**Pull request closed without merging**
