### PR TITLE
Created requestType Pages plus a prettier run

### LINKED ISSUE #23: Create RequestTypeCreatePage, RequestTypeIndexPage, RequestTypeEditPage
One of the sub issues corresponding to Feature: Request Types CRUD (Issue #11)

### LINKED ISSUE #51: Add RequestType in App.js

### PR DESCRIPTION
**Pull request by 17acastelein**
Closes #23 
Closes #51 

Added create, edit, and index pages for RequestType.
Added Request Type to App.js and navbar and replaced placeholders

Dokku deployment: https://rec-dev-ac.dokku-05.cs.ucsb.edu/

Screenshot 2024-11-26 at 3 27 53 PM
Screenshot 2024-11-26 at 3 28 56 PM
Screenshot 2024-11-26 at 3 27 14 PM

*Most of the files changed are due to the prettier run

### CODE REVIEW

**Review by bgggggh — DISMISSED** [review]
LGTM

**Review by RyanZanone — DISMISSED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
Combining a "prettier run" along with "substantive changes" violates the principle that a PR needs to be "about one thing".

It makes it very difficult to code review, because on the one hand, you have files that only have white space changes (dozens of them), while on the other hand you have files that have substantive changes.

That's why it's considered a bad practice in industry, and would likely lead to the PR being rejected.

What you should do is split this into two PRs.

Here's how:

```
git fetch origin
git checkout requestTypePages
git pull origin requestTypePages
```

Next, you are going to create a new branch for "just" the changes that pertain to request type.

```
git checkout -b RequestTypePagesV2 
```

To construct this branch, you need to do a `git reset --soft parent-SHA` where `parent-SHA` is the sha of the commit *right before* your first commit.  To find that, first look at the commits on your PR, which are these:

image

From that, we see that the oldest commit on this branch is `4d3d834`.  We want the parent of this commit.  To find it, we can use `git log --graph`.  As you can see, it takes a while to find it, but eventually we do:

image
image
image

The commit right before `4d3d834` is `b915e0e`

So that's the one we want.  We are going to do a `git reset --soft b915e0e` to get back to where we can separate the changes to set of files from the other.

Here's what that looks like. In this example I called it `newBranch` instead of `RequestTypePagesV2` but it's the same idea:

```
pconrad@Phillips-MacBook-Air-2 proj-rec-f24-05 % git checkout requestTypePages       
Switched to branch 'requestTypePages'
Your branch is up to date with 'origin/requestTypePages'.
pconrad@Phillips-MacBook-Air-2 proj-rec-f24-05 % git pull origin requestTypePages
From github.com:ucsb-cs156-f24/proj-rec-f24-05
 * branch              requestTypePages -> FETCH_HEAD
Already up to date.
pconrad@Phillips-MacBook-Air-2 proj-rec-f24-05 % git reset  b915e0e              
Unstaged changes after reset:
M	.env.SAMPLE
M	.github/workflows/82-kanban-slack-update.yml
M	frontend/.storybook/main.js
M	frontend/.storybook/preview.js
M	frontend/docs-index/_config.yml
M	frontend/docs-index/_layouts/default.html
M	frontend/docs-index/index.md
M	frontend/jsconfig.json
M	frontend/public/index.html
M	frontend/public/mockServiceWorker.js
M	frontend/src/App.js
M	frontend/src/fixtures/temp.json
M	frontend/src/index.css
M	frontend/src/main/components/Nav/AppNavbar.js
M	frontend/stryker.config.json
M	src/main/resources/db/migration/changes/RequestTypes.json
pconrad@Phillips-MacBook-Air-2 proj-rec-f24-05 % 
```

Then the git status is this:

What we *want* for this branch is to only commit the changes to the files that are substantive changes to the request pages (not the whitespace only changes)

I'm not going to go through and figure out which is which: THAT IS YOUR JOB.

But once you figure that out, for example, in this case, we'd want to `git add filename` on each of those files one-by-one. That turns them green:

For instance, I'm assuming that `frontend/src/main/pages/RequestType/RequestTypeCreatePage.js` is one of the pages you want in your PR.

So do: `git add frontend/src/main/pages/RequestType/RequestTypeCreatePage.js`

Then you have: 

image

Repeat until you have *only* the files you want in your PR. Then commit that, push the new branch, and make a new PR to replace this one.

If you also want to update the files with prettier, do that in a *separate* PR that you base off the main branch, and in which that is *all* that you do.

**Comment by pconrad** [comment]
Replaced by #79

**Pull request closed without merging**
