### PR TITLE
Added Request Type form files, Added Request Type fixtures

### LINKED ISSUE #20: Create RequestTypeForm (team02 style)
One of the sub issues corresponding to Feature: Request Types CRUD (Issue #11)

### PR DESCRIPTION
**Pull request by Bruhwilliam**
Storybook: https://6734fd9d9ba3658d415f4ecc-yqgwpmzoxk.chromatic.com/?path=/docs/components-requesttypes-requesttypeform--docs

Closes #20 
Note: 
-Added Entity, Repository, and db migration file from rz-backendRequestTypeTable

Screenshot 2024-11-23 at 1 50 42 PM
Screenshot 2024-11-23 at 1 50 50 PM

### CODE REVIEW

**Review by RyanZanone — APPROVED** [review]
LGTM

**Review by pconrad — COMMENTED** [review]
Not mergeable at the moment because of merge conflicts.

**Review by pconrad — APPROVED** [review]
LGTM

**Review by basperheim1 — APPROVED** [review]
LGTM

**Pull request merged**
